import "./globals.css";
import ReduxWrapper from "@/components/ReduxWrapper/ReduxWrapper";
import ReduxProvider from "@/components/ReduxProvider/ReduxProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReduxProvider>
        <ReduxWrapper>{children}</ReduxWrapper>
      </ReduxProvider>
    </html>
  );
}
